### ISSUE TITLE
Possible to extract z-order curve as a lib?

### ISSUE THREAD

**Issue by fire** [g-andrade/erlzquad#1]
Would be useful to extract z-order curve as a library.

**Comment by g-andrade** [comment]
Mmh, that's very reasonable. I'll look into it if I get the chance.

**Comment by fire** [comment]
I was trying to use the z-order curve for three dimensions. The algorithm says it should be possible for n dimensions. Do you know how hard it is to convert the z-order code you have to three dimensions or n?

My main language is https://github.com/dazuma/erl2ex  So I tried converting it to elixir and it seemed to work.

**Comment by g-andrade** [comment]
I made an integer-only approach at [g-andrade/erlzord](https://github.com/g-andrade/erlzord) - a work in progress.

It works with 0 or more dimensions and one specifies the range of the coordinate values in order to determine bitsizes:

```erlang
% 2-dimensional points with each coordinate between 0 and 7 (closed interval)
erlzord:calculate({0,0}, 0, 7). % 0
erlzord:calculate({0,1}, 0, 7). % 2
erlzord:calculate({1,0}, 0, 7). % 1
erlzord:calculate({1,1}, 0, 7). % 3
% ...
erlzord:calculate({7,7}, 0, 7). % 63
```

As far as I can tell the algorithm is entirely generic, but I'll still need to improve test coverage. What do you think?

**Comment by fire** [comment]
Look good, I was wondering what approach you would use to store positive and negative grids. I assume we just push the entire world into positive integers.

For example: using this for voxels.

**Comment by fire** [comment]
The algorithm if you want to review it is:

The algorithm is given x, y, z, data use a hash(x,y,z) as a key and then store a list of: location and a pointer to a bucket. The list in the hash table makes this a chaining hash table (collisions).

I take the space filling curve(x,y,z) and use it to find what 8^3 voxel bucket has and its associated data. Think using the remainder of n where n is the bucket size.

Brute force scan the hash table to find all the buckets. Use frustum culling on the associated buckets to get what a player sees.

[edited]

**Comment by g-andrade** [comment]
erlzord version 1.0.0 [released](https://github.com/g-andrade/erlzord/releases/tag/1.0.0). It supports both encoding and decoding of Z values. Range searches are still a to-do.

I've also made it available on [Hex](https://hex.pm/packages/erlzord) - you should be able to use directly from Elixir.
